name: fma_webview_flutter
description: A flutter_micro_app package that enables webviews comunication
version: 0.1.0
homepage: https://github.com/emanuel-braz/fma_webview_flutter

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.4
  flutter_micro_app: 0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
